services:
  simulation:
    build: ./simulation/
    ports:
      - "8000:8000"
  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: "db.env"