Create table internet_router ( time timestamptz primary key, data float8); 
select create_hypertable('internet_router',by_range('time'));
Create table printer_3D ( time timestamptz primary key, data float8);          
select create_hypertable('printer_3D',by_range('time'));
Create table air_conditioner ( time timestamptz primary key, data float8);     
select create_hypertable('air_conditioner',by_range('time'));
Create table laptop ( time timestamptz primary key, data float8); 
select create_hypertable('laptop',by_range('time'));
Create table air_purifier ( time timestamptz primary key, data float8);      
select create_hypertable('air_purifier',by_range('time'));
Create table boiler ( time timestamptz primary key, data float8);              
select create_hypertable('boiler',by_range('time'));
Create table micro_wave_oven ( time timestamptz primary key, data float8); 
select create_hypertable('micro_wave_oven',by_range('time'));
Create table phone_charger ( time timestamptz primary key, data float8); 
select create_hypertable('phone_charger',by_range('time'));
Create table printer ( time timestamptz primary key, data float8);
select create_hypertable('printer',by_range('time'));
Create table coffee ( time timestamptz primary key, data float8);               
select create_hypertable('coffee',by_range('time'));
Create table radiator ( time timestamptz primary key, data float8); 
select create_hypertable('radiator',by_range('time'));
Create table screen ( time timestamptz primary key, data float8); 
select create_hypertable('screen',by_range('time'));
Create table computer ( time timestamptz primary key, data float8);             
select create_hypertable('computer',by_range('time'));
Create table solar_panel ( time timestamptz primary key, data float8); 
select create_hypertable('solar_panel',by_range('time'));
Create table sound_system ( time timestamptz primary key, data float8); 
select create_hypertable('sound_system',by_range('time'));
Create table dehumidifier ( time timestamptz primary key, data float8);        
select create_hypertable('dehumidifier',by_range('time'));
Create table tv ( time timestamptz primary key, data float8); 
select create_hypertable('tv',by_range('time'));
Create table dishwasher ( time timestamptz primary key, data float8);           
select create_hypertable('dishwasher',by_range('time'));
Create table dryer ( time timestamptz primary key, data float8);               
select create_hypertable('dryer',by_range('time'));
Create table vacuum ( time timestamptz primary key, data float8);
select create_hypertable('vacuum',by_range('time'));
Create table fan ( time timestamptz primary key, data float8);                  
select create_hypertable('fan',by_range('time'));
Create table washing_machine ( time timestamptz primary key, data float8);             
select create_hypertable('washing_machine',by_range('time'));
Create table fridge ( time timestamptz primary key, data float8);             
select create_hypertable('fridge',by_range('time'));
Create table freezer ( time timestamptz primary key, data float8);             
select create_hypertable('freezer',by_range('time'));
