name: Deploy

permissions: { }

on:
  push:
    branches: ["feature/deploy"]

jobs:
  rust-test:
    uses: ./.github/workflows/rust.yml
  create-envfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Make agent .env 
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PASSWORD : ${{ secrets.AGENT_PASSWORD }}
          directory : backend/agent 
          file_name: .env

      - name: Make market-platfrom .env 
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.MARKET_DATABASE_URL }}
          envkey_GRID_URL: ${{ vars.MARKET_GRID_URL }}
          envkey_FRONTEND_URL: ${{ vars.MARKET_FRONTEND_URL}}
          directory: backend/market-platform 
          file_name: .env


