name: linter

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write # Updates commit statuses

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          # linter requires full git history
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Super-Linter
        uses: super-linter/super-linter@v6.5.0
        env: 
          # To report status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

