[package]
name = "agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = {version = "1.0.204", features = ["rc", "derive"]}
serde_json = "1.0.120"
tungstenite = "0.23.0"
dotenvy = "0.15.7"
